# version: '3.8'

# services:
#   php:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "4000:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: ""
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql for database initialization
#     command: --init-file /docker-entrypoint-initdb.d/init.sql

# volumes:
#   mysql_data:


####################


